// Generated by CoffeeScript 1.6.3
angular.module('AMail.directives', []).directive('ngbkFocus', function() {
  return {
    link: function(scope, element, attrs, controller) {
      element[0].focus();
    }
  };
});
