// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http, serv;



  http = require('http');

  serv = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end('<marquee>Smashing Node!</marquee>');
  });

  serv.listen(3000);

}).call(this);
