// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var bar, foo, start;



  start = Date.now();

  foo = function() {
    var i, _i;
    console.log(Date.now() - start);
    for (i = _i = 0; _i <= 10000000; i = ++_i) {
      i;
    }
  };

  setTimeout(foo, 1000);

  bar = function() {
    return console.log(Date.now() - start);
  };

  setTimeout(bar, 2000);

}).call(this);
