// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http;



  http = require('http');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    res.end('<h1>Hello world!</h1>');
  }).listen(3000);

}).call(this);
