// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var a, b, c;



  c = function() {
    return b();
  };

  b = function() {
    return a();
  };

  a = function() {
    throw new Error('Error yay!');
  };

  c();

}).call(this);
