// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var privateVar;



  exports.name = 'john';

  exports.data = 'some data';

  privateVar = 5;

  exports.getPrivate = function() {
    return privateVar;
  };

}).call(this);
