// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var Person;



  Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.talk = function() {
      return console.log("my name is " + this.name);
    };

    return Person;

  })();

  module.exports = Person;

}).call(this);
