// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http, serv;



  http = require('http');

  serv = http.createServer(function() {
    throw new Error('This will be uncaught.');
  });

  serv.listen(3000);

  process.on('uncaughtException', function(err) {
    console.error(err);
    process.exit(1);
  });

}).call(this);
