// Generated by CoffeeScript 1.6.3
var MyClass, mc1, mc2, module;

module = (function() {
  var privateProperty;
  privateProperty = 1;
  return {
    publicProperty: privateProperty,
    someFunction: function() {
      console.log('basically does nothing');
    }
  };
})();

console.log(module.publicProperty);

module.someFunction();

MyClass = (function() {
  function MyClass(name) {
    this.name = name;
    console.log('constructing');
  }

  MyClass.prototype.someMethod = function() {
    return console.log('someMethod called');
  };

  MyClass.someProperty = '@someProperty';

  MyClass.prototype.someProperty = 'someProperty';

  MyClass.someOtherMethod = function() {
    return console.log(someProperty);
  };

  return MyClass;

})();

mc1 = new MyClass('mc1');

mc1.someMethod();

console.log(mc1.someProperty);

mc2 = new MyClass('mc2');
