// Generated by CoffeeScript 1.6.3
var Observer;

Observer = (function() {
  function Observer() {
    this.observerList = [];
  }

  Observer.prototype.add = function(obj) {
    return this.observerList.push(obj);
  };

  Observer.prototype.count = function() {
    return this.observerList.length;
  };

  Observer.prototype.empty = function() {
    return this.observerList = [];
  };

  Observer.prototype.get = function(ind) {
    if ((0 <= ind && ind < this.observerList.length)) {
      return this.observerList[ind];
    }
  };

  Observer.prototype.insert = function(obj, ind) {
    return ([].splice.apply(this.observerList, [ind, ind - ind].concat(obj)), obj);
  };

  return Observer;

})();
