// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http, qs, server;



  http = require('http');

  qs = require('querystring');

  server = http.createServer(function(req, res) {
    var body;
    if (req.url === '/') {
      res.writeHead(200, {
        'Content-Type': 'text/html'
      });
      res.end(['<form method="post" action="url">', '<h1>My Form</h1>', '<fieldset>', '<label>Personal Information</label>', '<p>What is your name?</p>', '<input type="text" name="name">', '<p><input type="submit" valuen="Submit"></p>', '</fieldset>', '</form>'].join(''));
    } else if (req.url === '/url' && req.method === 'POST') {
      body = '';
      req.on('data', function(chunk) {
        body += chunk;
      });
      req.on('end', function() {
        res.writeHead(200, {
          'Content-Type': 'text/html'
        });
        console.log(qs.parse(body));
        res.end("<p>Your name is <b>" + (qs.parse(body).name) + "</b>.</p>");
      });
    } else {
      res.writeHead(404);
      res.end('Not Found');
    }
  });

  server.listen(3000);

}).call(this);
