// Generated by CoffeeScript 1.6.2
(function() {
  var x, _fn, _i, _j, _len, _len1, _ref, _ref1;

  _ref = [1, 2];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    x = _ref[_i];
    setTimeout((function() {
      return console.log(x);
    }), 50);
  }

  _ref1 = [1, 2];
  _fn = function(x) {
    return setTimeout((function() {
      return console.log(x);
    }), 50);
  };
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    x = _ref1[_j];
    _fn(x);
  }

}).call(this);
