// Generated by CoffeeScript 1.6.2
(function() {
  var a, clearArray, fun, run, showAnswer, what, x, xInContext,
    __slice = [].slice;

  clearArray = function(array) {
    array.splice(0, array.length);
    array;
  };

  a = [1, 2, 3, 4];

  console.log(clearArray(a));

  run = function() {
    var args, func;

    func = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return func.apply(null, args);
  };

  fun = function(arg1, arg2) {
    console.log(arg1);
    return console.log(arg2);
  };

  run(fun, 'hey', 'I just met you', 'yeah');

  xInContext = function() {
    return console.log(this.x);
  };

  what = {
    x: 'quantum entaglement'
  };

  xInContext.call(what);

  x = true;

  showAnswer = function(x) {
    if (x == null) {
      x = x;
    }
    console.log(x);
    return console.log(x ? 'It works!' : 'Nay..');
  };

  showAnswer();

}).call(this);
