// Generated by CoffeeScript 1.6.2
(function() {
  var $, Dog, age, callback, cat, cube, d1, d2, e, greeting, h1, odd, pig, reincarnate, setName, setProp, singCountdown, x, y,
    _this = this,
    __slice = [].slice;

  console.log("Hello world!");

  console.log((function() {
    return "Hello functions!";
  })());

  h1 = function() {
    return "Hello functions v2!";
  };

  console.log(h1());

  greeting = function(subject) {
    return "Hello, " + subject;
  };

  console.log(greeting('arguments'));

  cube = function(num) {
    return Math.pow(num, 3);
  };

  console.log(cube(2));

  odd = function(num) {
    if (typeof num === 'number') {
      if (num === Math.round(num)) {
        if (num > 0) {
          return num % 2 === 1;
        } else {
          throw "" + num + " is not positive";
        }
      } else {
        throw "" + num + " is not an integer";
      }
    } else {
      throw "" + num + " is not a number";
    }
  };

  try {
    odd(5.1);
  } catch (_error) {
    e = _error;
    console.log(e);
  }

  $ = function(arg) {
    return {
      each: function() {
        return true;
      }
    };
  };

  console.log(($('p')).each());

  try {
    odd('5.1');
  } catch (_error) {
    e = _error;
    console.log(e);
  }

  try {
    odd(-3);
  } catch (_error) {
    e = _error;
    console.log(e);
  }

  x = 1;

  y = function() {
    console.log(x);
    x = 2;
    return console.log(x);
  };

  console.log(y());

  console.log(x);

  reincarnate = function() {
    var age;

    return age = 0;
  };

  age = 99;

  reincarnate();

  console.log("Age: " + age);

  singCountdown = function(count) {
    var singBottleCount, singDecrement;

    singBottleCount = function(specifyLocation) {
      var bottleStr, locationStr;

      locationStr = specifyLocation ? 'on the wall' : '';
      bottleStr = count === 1 ? 'bottle' : 'bottles';
      return console.log("" + count + " " + bottleStr + " of beer " + locationStr);
    };
    singDecrement = function() {
      console.log('Take one down, pass it around');
      return count--;
    };
    singBottleCount(true);
    singBottleCount(false);
    singDecrement();
    singBottleCount(false);
    if (count !== 0) {
      return singCountdown(count);
    }
  };

  singCountdown(5);

  setName = function(name) {
    this.name = name;
  };

  cat = {};

  cat.setName = setName;

  cat.setName('Mingming');

  console.log(cat.name);

  pig = {};

  setName.apply(pig, ['Babs']);

  console.log(pig.name);

  Dog = setName;

  d1 = new Dog('D1');

  d2 = new Dog('D2');

  console.log(d1.name);

  console.log(d2.name);

  setName('Lulu');

  console.log(name);

  console.log(global.name);

  console.log(this.name);

  callback = function(message) {
    return _this.voicemail.push(message);
  };

  console.log('yey');

  setProp = function(prop) {
    this.prop = prop;
  };

  console.log.apply(console, __slice.call([1, 2, 3]).concat([4]));

}).call(this);
