// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var fs, http, server;



  http = require('http');

  fs = require('fs');

  server = http.createServer(function(req, res) {
    var filepath, http404, serve;
    serve = function(path, type) {
      res.writeHead(200, {
        'Content-Type': type
      });
      return fs.createReadStream(path).pipe(res);
    };
    http404 = function(msg) {
      res.writeHead(404);
      return res.end(msg);
    };
    if (req.method === 'GET' && req.url.substr(0, 7) === '/images' && req.url.substr(-4) === '.jpg') {
      filepath = __dirname + '/../../' + req.url;
      console.log(filepath);
      fs.stat(filepath, function(err, stat) {
        if (err || !stat.isFile()) {
          http404('Not Found');
        } else {
          serve(filepath, 'image/jpg');
        }
      });
    } else if (req.method === 'GET' && req.url === '/') {
      console.log('serving index.html');
      serve(__dirname + '/../../index.html', 'text/html');
    } else {
      http404('Not Found');
    }
  });

  server.listen(3000);

}).call(this);
