// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http, qs, server;



  http = require('http');

  qs = require('querystring');

  server = http.createServer(function(req, res) {
    var body;
    body = '';
    req.on('data', function(chunk) {
      return body += chunk;
    });
    return req.on('end', function() {
      res.writeHead(200);
      return setTimeout(function() {
        res.end('Done');
        return console.log("Got name: " + (qs.parse(body).name));
      }, 5000);
    });
  });

  server.listen(3000);

}).call(this);
