// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var http, options, qs, req, search;



  http = require('http');

  qs = require('querystring');

  search = process.argv.slice(2).join(' ').trim();

  if (!search.length) {
    console.log('\nUsage: node tweets <search_term>');
  }

  console.log("searching for: " + search);

  options = {
    host: 'api.twitter.com',
    path: '/1.1/search/tweets.json?' + (qs.stringify({
      q: search
    }))
  };

  req = http.request(options, function(res) {
    var body;
    body = '';
    res.setEncoding('utf8');
    res.on('data', function(chunk) {
      return body += chunk;
    });
    return res.on('end', function() {
      var obj, tweet, _i, _len, _ref, _results;
      obj = JSON.parse(body);
      _ref = obj.statuses;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tweet = _ref[_i];
        _results.push((function(tweet) {
          console.log(tweet.text);
          return console.log('--');
        })(tweet));
      }
      return _results;
    });
  });

}).call(this);
