// Generated by CoffeeScript 1.6.3
var WorkLogger;

WorkLogger = angular.module('WorkLogger', ['ngCookies']);

WorkLogger.controller('WorkLoggerCtrl', function($scope, $cookies, $filter, $http) {
  var getProjectName, updatePage;
  getProjectName = function(entry) {
    return $http.get(entry.project).success(function(data, status, headers, config) {
      return entry.projectName = data.name;
    });
  };
  updatePage = function(formattedDate) {
    return $http.get("/api/v1/logentry/?format=json&date=" + formattedDate).success(function(data, status, headers, config) {
      var e, _i, _len, _ref;
      $scope.current_user = data.current_user;
      $scope.viewed_date = $filter('date')(data.viewed_date, 'yyyy-MM-dd');
      _ref = data.objects;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        getProjectName(e);
      }
      $scope.entries = data.objects;
      $scope.daily_total = data.daily_total;
      $scope.weekly_total = data.weekly_total;
      $scope.monthly_total = data.monthly_total;
      $scope.date = $scope.viewed_date;
      $scope.duration = 0.0;
      return $http.get("/api/v1/project/?format=json&members=" + $scope.current_user.pk).success(function(data, status, headers, config) {
        return $scope.projects = data.objects;
      });
    });
  };
  $scope.init = function() {
    var current_date, date_created;
    current_date = new Date();
    date_created = $filter('date')(current_date.valueOf(), 'yyyy-MM-dd');
    return updatePage(date_created);
  };
  $scope.viewDate = function() {
    return updatePage($scope.viewed_date);
  };
  return $scope.createLogEntry = function() {
    $http.defaults.headers.post['X-CSRFToken'] = $cookies.csrftoken;
    return $http.post("/api/v1/logentry/", {
      user: "/api/v1/user/" + $scope.current_user.pk + "/",
      date: $scope.date,
      duration: $scope.duration,
      project: $scope.project,
      remarks: $scope.remarks
    }).success(function(data, status, headers, config) {
      return updatePage($scope.viewed_date);
    });
  };
});
